apiVersion: skaffold/v2beta16
kind: Config

build:
  artifacts:
  - image: node-example
    context: backend
    docker:
      buildArgs:
        A_BUILD_TOKEN: '{{.AN_ENV_VARIABLE}}'
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: node-example
        context: backend
        docker:
          buildArgs:
            ENV: development
        sync:
          manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.js'
            dest: .